name: clang-analyze

on: [push, pull_request]

jobs:
  clang-analyze:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install clang-tools-10
      run: sudo apt-get update && sudo apt-get install -yq clang-tools-10

    - name: Create Build Environment
      run: scan-build-10 cmake -E make_directory build

    - name: Configure
      working-directory: build/
      run: scan-build-10 cmake $GITHUB_WORKSPACE

    - name: Build
      working-directory: build/
      run: scan-build-10 cmake --build .
