name: Code Coverage

on: [push, pull_request]

jobs:
  code_coverage:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory build

    - name: Configure
      working-directory: build/
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-coverage"

    - name: Build
      working-directory: build/
      run: cmake --build . --config Debug

    - name: Test
      working-directory: build/
      run: ctest -C Debug --output-on-failure

    - name: Collect code coverage
      working-directory: build/
      run: bash <(curl -s https://codecov.io/bash)
