name: macOS

on: [push, pull_request]

jobs:
  xcode:
    strategy:
      fail-fast: false
      matrix:
        xcode: ['10', '11', '12']
        build_type: [Debug, Release]

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode }}

    - name: Create Build Environment
      run: cmake -E make_directory build

    - name: Configure
      working-directory: build/
      run: cmake $GITHUB_WORKSPACE

    - name: Build
      working-directory: build/
      run: cmake --build . --config ${{ matrix.build_type }}

#    - name: Test
#      working-directory: build/
#      run: ctest --config ${{ matrix.build_type }} --output-on-failure
