name: Sanitizer

on: [push, pull_request]

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        image: [gcc10, clang11]
        sanitizer: [address, undefined]

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      TAOPQ_TEST_DATABASE: host=postgres dbname=postgres user=postgres password=postgres

    container:
      image: conanio/${{ matrix.image }}
      options: --user root

    steps:
    - uses: actions/checkout@v2

    - name: Install libpq-dev
      run: sudo apt-get update && sudo apt-get install -yq libpq-dev postgresql-server-dev-all

    - name: Create Build Environment
      run: cmake -E make_directory build

    - name: Configure
      working-directory: build/
      run: cmake $GITHUB_WORKSPACE -DCMAKE_CXX_FLAGS="-fsanitize=${{ matrix.sanitizer }}"

    - name: Build
      working-directory: build/
      run: cmake --build .

    - name: Test
      working-directory: build/
      run: ctest --output-on-failure
