name: Windows

on: [push, pull_request]

jobs:
  vs2019:
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    runs-on: windows-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      TAOPQ_TEST_DATABASE: host=postgres dbname=postgres user=postgres password=postgres

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory build

    - name: Configure
      shell: bash
      working-directory: build/
      run: cmake $GITHUB_WORKSPACE -G "Visual Studio 16 2019"

    - name: Build
      working-directory: build/
      run: cmake --build . --config ${{ matrix.build_type }}

    - name: Test
      working-directory: build/
      run: ctest -C ${{ matrix.build_type }} --output-on-failure

  vs2019-clang:
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    runs-on: windows-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      TAOPQ_TEST_DATABASE: host=postgres dbname=postgres user=postgres password=postgres

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory build

    - name: Configure
      shell: bash
      working-directory: build/
      run: cmake $GITHUB_WORKSPACE -G "Visual Studio 16 2019" -T ClangCL

    - name: Build
      working-directory: build/
      run: cmake --build . --config ${{ matrix.build_type }}

    - name: Test
      working-directory: build/
      run: ctest -C ${{ matrix.build_type }} --output-on-failure

  vs2017:
    strategy:
      fail-fast: false
      matrix:
        visual_studio:
          - 'Visual Studio 15 2017'
          - 'Visual Studio 15 2017 Win64'
        build_type: [Debug, Release]

    runs-on: windows-2016

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      TAOPQ_TEST_DATABASE: host=postgres dbname=postgres user=postgres password=postgres

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory build

    - name: Configure
      shell: bash
      working-directory: build/
      run: cmake $GITHUB_WORKSPACE -G "${{ matrix.visual_studio }}"

    - name: Build
      working-directory: build/
      run: cmake --build . --config ${{ matrix.build_type }}

    - name: Test
      working-directory: build/
      run: ctest -C ${{ matrix.build_type }} --output-on-failure
